// Supabase Configuration
// This file is automatically generated when connecting to Supabase project
// Project ID: fzsqmwqhiyitkjlbdyow

class SupabaseConfig {
  static const String supabaseUrl = 'https://fzsqmwqhiyitkjlbdyow.supabase.co';
  static const String supabaseAnonKey = 'eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImZ6c3Ftd3FoaXlpdGtqbGJkeW93Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3Njg3NDgxMTgsImV4cCI6MjA4NDMyNDExOH0.vw1R3NTetSe1KaJoUUxL6ePy4MRuHPKKAKmFulp4w4s';
}
