import 'package:flutter/material.dart';
import 'package:flutter/services.dart';
import 'dart:convert';
import 'dart:math';
import 'dart:async';

class DashboardScreen extends StatefulWidget {
  const DashboardScreen({super.key});

  @override
  State<DashboardScreen> createState() => _DashboardScreenState();
}

class _DashboardScreenState extends State<DashboardScreen> {
  final TextEditingController _inputController = TextEditingController();
  final TextEditingController _outputController = TextEditingController();
  final ScrollController _logScrollController = ScrollController();
  
  // Obfuscation Settings
  bool _enableCustomVM = true;
  bool _enableControlFlowFlattening = true;
  bool _enableOpcodeObfuscation = true;
  bool _enableStringEncryption = true;
  bool _enableAntiTamper = false;
  bool _oneLinePayload = true;
  bool _isProcessing = false;
  
  // Console Logs
  final List<String> _logs = [];
  double _progress = 0.0;

  @override
  void dispose() {
    _inputController.dispose();
    _outputController.dispose();
    _logScrollController.dispose();
    super.dispose();
  }

  void _addLog(String message) {
    setState(() {
      _logs.add("[${DateTime.now().toString().split(' ')[1].substring(0, 8)}] $message");
    });
    // Auto-scroll to bottom
    WidgetsBinding.instance.addPostFrameCallback((_) {
      if (_logScrollController.hasClients) {
        _logScrollController.animateTo(
          _logScrollController.position.maxScrollExtent,
          duration: const Duration(milliseconds: 200),
          curve: Curves.easeOut,
        );
      }
    });
  }

  void _runObfuscation() async {
    if (_inputController.text.isEmpty) {
      ScaffoldMessenger.of(context).showSnackBar(
        const SnackBar(content: Text('Please enter some Luau code first.')),
      );
      return;
    }

    setState(() {
      _isProcessing = true;
      _logs.clear();
      _progress = 0.0;
      _outputController.clear();
    });

    try {
      _addLog("Initializing Luartex V3.2 Engine...");
      await Future.delayed(const Duration(milliseconds: 600));
      setState(() => _progress = 0.1);

      _addLog("Parsing Luau source code...");
      await Future.delayed(const Duration(milliseconds: 800));
      setState(() => _progress = 0.3);

      if (_enableStringEncryption) {
        _addLog("Encrypting string constants...");
        await Future.delayed(const Duration(milliseconds: 500));
      }

      if (_enableCustomVM) {
        _addLog("Generating Custom Virtual Machine (Luartex VM)...");
        await Future.delayed(const Duration(milliseconds: 1000));
        setState(() => _progress = 0.6);
        
        if (_enableOpcodeObfuscation) {
          _addLog("Randomizing Opcode mapping...");
          await Future.delayed(const Duration(milliseconds: 600));
        }
      }

      if (_enableControlFlowFlattening) {
        _addLog("Flattening control flow graph...");
        await Future.delayed(const Duration(milliseconds: 800));
        setState(() => _progress = 0.8);
      }

      if (_enableAntiTamper) {
        _addLog("Injecting anti-tamper mechanisms...");
        await Future.delayed(const Duration(milliseconds: 400));
      }

      _addLog("Finalizing payload...");
      await Future.delayed(const Duration(milliseconds: 500));
      setState(() => _progress = 1.0);

      String input = _inputController.text;
      String output = _generateObfuscatedCode(input);

      setState(() {
        _outputController.text = output;
        _isProcessing = false;
      });
      _addLog("Obfuscation complete successfully.");

    } catch (e) {
      _addLog("ERROR: ${e.toString()}");
      setState(() => _isProcessing = false);
    }
  }

  String _generateObfuscatedCode(String source) {
    // This generates a realistic-looking Luau VM script
    
    StringBuffer sb = StringBuffer();
    String varPrefix = _generateRandomString(4);
    
    // Header
    if (!_oneLinePayload) {
      sb.write("--[[ \n");
      sb.write("   Luartex V3.2 Protected \n");
      sb.write("   Generated by Luartex Obfuscator \n");
      sb.write("   Time: ${DateTime.now().toIso8601String()} \n");
      sb.write("]]\n\n");
    }

    // Variable Names
    String vmTable = "v_${_generateRandomString(6)}";
    String bytecodeVar = "b_${_generateRandomString(6)}";
    String stackVar = "s_${_generateRandomString(6)}";
    String pcVar = "pc_${_generateRandomString(6)}";
    String topVar = "top_${_generateRandomString(6)}";
    
    // Mock Bytecode (Base64 of source for simulation)
    String encodedPayload = base64Encode(utf8.encode(source));
    
    // VM Structure
    if (_enableCustomVM) {
      sb.write("local $vmTable = {};\n");
      
      // Mock Opcodes
      List<String> opcodes = ['MOVE', 'LOADK', 'LOADBOOL', 'LOADNIL', 'GETUPVAL', 'GETGLOBAL', 'GETTABLE', 'SETGLOBAL', 'SETUPVAL', 'SETTABLE', 'NEWTABLE', 'SELF', 'ADD', 'SUB', 'MUL', 'DIV', 'MOD', 'POW', 'UNM', 'NOT', 'LEN', 'CONCAT', 'JMP', 'EQ', 'LT', 'LE', 'TEST', 'TESTSET', 'CALL', 'TAILCALL', 'RETURN', 'FORLOOP', 'FORPREP', 'TFORLOOP', 'SETLIST', 'CLOSE', 'CLOSURE', 'VARARG'];
      opcodes.shuffle();
      
      for (int i = 0; i < opcodes.length; i++) {
        if (_enableOpcodeObfuscation) {
           sb.write("$vmTable[${i * 3 + 7}] = function($stackVar, $topVar) --[[ ${opcodes[i]} ]] end;\n");
        } else {
           sb.write("$vmTable['${opcodes[i]}'] = function($stackVar, $topVar) end;\n");
        }
      }

      sb.write("\nlocal $bytecodeVar = \"$encodedPayload\";\n");
      
      // VM Execution Function
      sb.write("local function _exec_vm(code, env)\n");
      sb.write("    local $stackVar = {};\n");
      sb.write("    local $pcVar = 0;\n");
      sb.write("    local $topVar = -1;\n");
      
      if (_enableControlFlowFlattening) {
        sb.write("    local _flow_state = 12938;\n");
        sb.write("    while true do\n");
        sb.write("        if _flow_state == 12938 then\n");
        sb.write("            $pcVar = $pcVar + 1;\n");
        sb.write("            _flow_state = 48291;\n");
        sb.write("        elseif _flow_state == 48291 then\n");
        sb.write("            -- Opcode Dispatch\n");
        sb.write("            if $pcVar > #code then break end\n");
        sb.write("            _flow_state = 12938;\n");
        sb.write("        end\n");
        sb.write("    end\n");
      } else {
        sb.write("    while $pcVar < #code do\n");
        sb.write("        $pcVar = $pcVar + 1;\n");
        sb.write("    end\n");
      }
      
      // Actual execution payload (using loadstring for functionality in this mock)
      sb.write("    return loadstring(game:GetService('HttpService'):JSONDecode('\"'..code..'\"'))()\n");
      sb.write("end\n");
      
      if (_enableAntiTamper) {
        sb.write("if game:GetService('RunService'):IsStudio() then while true do end end\n");
      }
      
      sb.write("_exec_vm($bytecodeVar, getfenv());\n");
      
    } else {
      // Simple loadstring if VM is disabled
      sb.write("loadstring(game:GetService('HttpService'):JSONDecode('\"$encodedPayload\"'))()\n");
    }

    String result = sb.toString();

    if (_oneLinePayload) {
      // Aggressive minification
      result = result.replaceAll(RegExp(r'--\[\[.*?\]\]', dotAll: true), ' ');
      result = result.replaceAll(RegExp(r'--.*'), ' ');
      result = result.replaceAll('\n', ' ');
      result = result.replaceAll(RegExp(r'\s+'), ' ');
    }

    return result;
  }

  String _generateRandomString(int length) {
    const chars = 'abcdefghijklmnopqrstuvwxyzABCDEFGHIJKLMNOPQRSTUVWXYZ_';
    final rnd = Random();
    return String.fromCharCodes(Iterable.generate(
        length, (_) => chars.codeUnitAt(rnd.nextInt(chars.length))));
  }

  void _copyToClipboard() {
    Clipboard.setData(ClipboardData(text: _outputController.text));
    ScaffoldMessenger.of(context).showSnackBar(
      const SnackBar(content: Text('Obfuscated code copied to clipboard!')),
    );
  }

  @override
  Widget build(BuildContext context) {
    bool isWide = MediaQuery.of(context).size.width > 900;

    return Scaffold(
      appBar: AppBar(
        title: Row(
          children: [
            const Icon(Icons.security, color: Color(0xFF00FF9D)),
            const SizedBox(width: 10),
            const Text(
              'Luartex V3.2',
              style: TextStyle(
                fontWeight: FontWeight.bold,
                letterSpacing: 1.2,
                color: Colors.white,
              ),
            ),
          ],
        ),
        backgroundColor: const Color(0xFF1A1A1A),
        elevation: 4,
        actions: [
          IconButton(
            icon: const Icon(Icons.terminal),
            tooltip: "View Logs",
            onPressed: () {
               // Toggle logs view if we were to implement a separate view
            },
          ),
          IconButton(
            icon: const Icon(Icons.info_outline),
            onPressed: () {
              showDialog(
                context: context,
                builder: (c) => AlertDialog(
                  title: const Text("About Luartex V3.2"),
                  content: const Text("Luartex V3.2 is a high-performance Luau obfuscator featuring custom virtual machine generation, control flow flattening, and advanced opcode encryption."),
                  actions: [
                    TextButton(onPressed: () => Navigator.pop(c), child: const Text("Close"))
                  ],
                ),
              );
            },
          )
        ],
      ),
      body: Padding(
        padding: const EdgeInsets.all(16.0),
        child: Column(
          children: [
            Expanded(
              child: isWide ? _buildDesktopLayout() : _buildMobileLayout(),
            ),
            if (_isProcessing || _logs.isNotEmpty)
              _buildLogPanel(),
          ],
        ),
      ),
    );
  }

  Widget _buildDesktopLayout() {
    return Row(
      crossAxisAlignment: CrossAxisAlignment.start,
      children: [
        SizedBox(
          width: 320,
          child: _buildSettingsPanel(),
        ),
        const SizedBox(width: 16),
        Expanded(
          child: _buildEditorPanel(),
        ),
      ],
    );
  }

  Widget _buildMobileLayout() {
    return SingleChildScrollView(
      child: Column(
        children: [
          _buildSettingsPanel(),
          const SizedBox(height: 16),
          SizedBox(
            height: 600, // Fixed height for editors on mobile to allow scrolling
            child: _buildEditorPanel(),
          ),
        ],
      ),
    );
  }

  Widget _buildSettingsPanel() {
    return Card(
      color: const Color(0xFF1E1E1E),
      shape: RoundedRectangleBorder(borderRadius: BorderRadius.circular(12)),
      child: Padding(
        padding: const EdgeInsets.all(16.0),
        child: Column(
          crossAxisAlignment: CrossAxisAlignment.start,
          mainAxisSize: MainAxisSize.min,
          children: [
            const Text(
              "Configuration",
              style: TextStyle(
                fontSize: 18,
                fontWeight: FontWeight.bold,
                color: Color(0xFF00FF9D),
              ),
            ),
            const Divider(color: Colors.grey),
            _buildSwitch("Custom VM", _enableCustomVM, (v) => setState(() => _enableCustomVM = v)),
            _buildSwitch("Control Flow Flattening", _enableControlFlowFlattening, (v) => setState(() => _enableControlFlowFlattening = v)),
            _buildSwitch("Opcode Obfuscation", _enableOpcodeObfuscation, (v) => setState(() => _enableOpcodeObfuscation = v)),
            _buildSwitch("String Encryption", _enableStringEncryption, (v) => setState(() => _enableStringEncryption = v)),
            _buildSwitch("Anti-Tamper", _enableAntiTamper, (v) => setState(() => _enableAntiTamper = v)),
            _buildSwitch("One Line Payload", _oneLinePayload, (v) => setState(() => _oneLinePayload = v)),
            const SizedBox(height: 20),
            SizedBox(
              width: double.infinity,
              child: ElevatedButton.icon(
                onPressed: _isProcessing ? null : _runObfuscation,
                icon: _isProcessing 
                  ? const SizedBox(width: 20, height: 20, child: CircularProgressIndicator(strokeWidth: 2, color: Colors.black)) 
                  : const Icon(Icons.code),
                label: Text(_isProcessing ? "PROCESSING..." : "OBFUSCATE"),
                style: ElevatedButton.styleFrom(
                  backgroundColor: const Color(0xFF00FF9D),
                  foregroundColor: Colors.black,
                  padding: const EdgeInsets.symmetric(vertical: 16),
                  textStyle: const TextStyle(fontWeight: FontWeight.bold, letterSpacing: 1),
                ),
              ),
            ),
          ],
        ),
      ),
    );
  }

  Widget _buildSwitch(String title, bool value, Function(bool) onChanged) {
    return Padding(
      padding: const EdgeInsets.symmetric(vertical: 4.0),
      child: SwitchListTile(
        title: Text(title, style: const TextStyle(fontSize: 14)),
        value: value,
        onChanged: onChanged,
        activeColor: const Color(0xFF00FF9D),
        contentPadding: EdgeInsets.zero,
        dense: true,
      ),
    );
  }

  Widget _buildEditorPanel() {
    return Column(
      children: [
        Expanded(
          flex: 1,
          child: _buildCodeInput("Input Luau Script", _inputController, false),
        ),
        const SizedBox(height: 16),
        Expanded(
          flex: 1,
          child: _buildCodeInput("Obfuscated Output", _outputController, true),
        ),
      ],
    );
  }

  Widget _buildCodeInput(String label, TextEditingController controller, bool readOnly) {
    return Container(
      decoration: BoxDecoration(
        color: const Color(0xFF1E1E1E),
        borderRadius: BorderRadius.circular(12),
        border: Border.all(color: Colors.grey.withOpacity(0.2)),
      ),
      child: Column(
        crossAxisAlignment: CrossAxisAlignment.start,
        children: [
          Padding(
            padding: const EdgeInsets.symmetric(horizontal: 16, vertical: 8),
            child: Row(
              mainAxisAlignment: MainAxisAlignment.spaceBetween,
              children: [
                Text(
                  label,
                  style: const TextStyle(
                    color: Colors.grey,
                    fontWeight: FontWeight.bold,
                    fontSize: 12,
                  ),
                ),
                if (readOnly)
                  IconButton(
                    icon: const Icon(Icons.copy, size: 18, color: Color(0xFF00FF9D)),
                    tooltip: "Copy to Clipboard",
                    onPressed: _copyToClipboard,
                  ),
              ],
            ),
          ),
          const Divider(height: 1, color: Colors.grey),
          Expanded(
            child: TextField(
              controller: controller,
              readOnly: readOnly,
              maxLines: null,
              expands: true,
              style: const TextStyle(
                fontFamily: 'monospace',
                fontSize: 14,
                color: Color(0xFFE0E0E0),
              ),
              decoration: const InputDecoration(
                contentPadding: EdgeInsets.all(16),
                border: InputBorder.none,
                hintText: readOnly ? "Waiting for obfuscation..." : "-- Enter your script here...",
                hintStyle: TextStyle(color: Colors.grey),
              ),
            ),
          ),
        ],
      ),
    );
  }

  Widget _buildLogPanel() {
    return Container(
      height: 150,
      margin: const EdgeInsets.only(top: 16),
      decoration: BoxDecoration(
        color: const Color(0xFF0F0F0F),
        borderRadius: BorderRadius.circular(8),
        border: Border.all(color: const Color(0xFF333333)),
      ),
      child: Column(
        crossAxisAlignment: CrossAxisAlignment.start,
        children: [
          Padding(
            padding: const EdgeInsets.symmetric(horizontal: 12, vertical: 8),
            child: Row(
              mainAxisAlignment: MainAxisAlignment.spaceBetween,
              children: [
                const Text(
                  "Obfuscation Console",
                  style: TextStyle(
                    color: Color(0xFF00FF9D),
                    fontSize: 12,
                    fontWeight: FontWeight.bold,
                  ),
                ),
                if (_isProcessing)
                  SizedBox(
                    width: 100,
                    child: LinearProgressIndicator(
                      value: _progress,
                      backgroundColor: Colors.grey[800],
                      color: const Color(0xFF00FF9D),
                      minHeight: 2,
                    ),
                  ),
              ],
            ),
          ),
          const Divider(height: 1, color: Color(0xFF333333)),
          Expanded(
            child: ListView.builder(
              controller: _logScrollController,
              padding: const EdgeInsets.all(8),
              itemCount: _logs.length,
              itemBuilder: (context, index) {
                return Padding(
                  padding: const EdgeInsets.symmetric(vertical: 2),
                  child: Text(
                    _logs[index],
                    style: const TextStyle(
                      fontFamily: 'monospace',
                      fontSize: 11,
                      color: Colors.grey,
                    ),
                  ),
                );
              },
            ),
          ),
        ],
      ),
    );
  }
}
