import 'package:flutter/material.dart';
import 'package:flutter/services.dart';
import 'dart:convert';
import 'dart:math';

class DashboardScreen extends StatefulWidget {
  const DashboardScreen({super.key});

  @override
  State<DashboardScreen> createState() => _DashboardScreenState();
}

class _DashboardScreenState extends State<DashboardScreen> {
  final TextEditingController _inputController = TextEditingController();
  final TextEditingController _outputController = TextEditingController();
  
  // Obfuscation Settings
  bool _enableCustomVM = true;
  bool _enableControlFlowFlattening = true;
  bool _enableOpcodeObfuscation = true;
  bool _enableStringEncryption = true;
  bool _enableAntiTamper = false;
  bool _oneLinePayload = true;
  bool _isProcessing = false;

  @override
  void dispose() {
    _inputController.dispose();
    _outputController.dispose();
    super.dispose();
  }

  void _runObfuscation() async {
    if (_inputController.text.isEmpty) {
      ScaffoldMessenger.of(context).showSnackBar(
        const SnackBar(content: Text('Please enter some Luau code first.')),
      );
      return;
    }

    setState(() {
      _isProcessing = true;
    });

    // Simulate processing delay for "heavy" obfuscation tasks
    await Future.delayed(const Duration(seconds: 1));

    String input = _inputController.text;
    String output = _mockObfuscate(input);

    setState(() {
      _outputController.text = output;
      _isProcessing = false;
    });
  }

  String _mockObfuscate(String source) {
    // This is a simulation of a Luau obfuscator. 
    // Real obfuscation requires a complex Lua parser and compiler.
    
    StringBuffer sb = StringBuffer();
    
    // Header
    sb.write("--[[ \n");
    sb.write("   Luartex V3.2 Protected \n");
    sb.write("   Generated by Luartex Obfuscator \n");
    sb.write("   Time: ${DateTime.now().toIso8601String()} \n");
    sb.write("]]\n");

    // Mock VM Structure
    String vmVar = _generateRandomString(6);
    String bytecodeVar = _generateRandomString(8);
    
    // Simple Base64 "Encryption" for the payload simulation
    String encodedPayload = base64Encode(utf8.encode(source));
    
    if (_enableCustomVM) {
      sb.write("local $vmVar = {};\n");
      sb.write("local $bytecodeVar = \"$encodedPayload\";\n");
      sb.write("local function _vm_exec(code) \n");
      sb.write("    -- Custom VM Opcode Interpretation Stub\n");
      sb.write("    local _stack = {};\n");
      sb.write("    local _pc = 0;\n");
      if (_enableControlFlowFlattening) {
        sb.write("    while true do\n");
        sb.write("        -- Control Flow Flattening Logic\n");
        sb.write("        if _pc == -1 then break end\n");
        sb.write("        _pc = _pc + 1\n");
        sb.write("    end\n");
      }
      sb.write("    return loadstring(game:GetService('HttpService'):JSONDecode('\"'..code..'\"'))()\n");
      sb.write("end\n");
      sb.write("_vm_exec($bytecodeVar);\n");
    } else {
      sb.write("loadstring(game:GetService('HttpService'):JSONDecode('\"$encodedPayload\"'))()\n");
    }

    String result = sb.toString();

    if (_oneLinePayload) {
      // Remove comments and newlines for one-line payload
      result = result.replaceAll(RegExp(r'--\[\[.*?\]\]', dotAll: true), '');
      result = result.replaceAll(RegExp(r'--.*'), '');
      result = result.replaceAll('\n', ' ');
      result = result.replaceAll(RegExp(r'\s+'), ' '); // Collapse spaces
    }

    return result;
  }

  String _generateRandomString(int length) {
    const chars = 'abcdefghijklmnopqrstuvwxyzABCDEFGHIJKLMNOPQRSTUVWXYZ_';
    final rnd = Random();
    return String.fromCharCodes(Iterable.generate(
        length, (_) => chars.codeUnitAt(rnd.nextInt(chars.length))));
  }

  void _copyToClipboard() {
    Clipboard.setData(ClipboardData(text: _outputController.text));
    ScaffoldMessenger.of(context).showSnackBar(
      const SnackBar(content: Text('Obfuscated code copied to clipboard!')),
    );
  }

  @override
  Widget build(BuildContext context) {
    // Determine if we are on a wide screen
    bool isWide = MediaQuery.of(context).size.width > 800;

    return Scaffold(
      appBar: AppBar(
        title: Row(
          children: [
            const Icon(Icons.security, color: Color(0xFF00FF9D)),
            const SizedBox(width: 10),
            const Text(
              'Luartex V3.2',
              style: TextStyle(
                fontWeight: FontWeight.bold,
                letterSpacing: 1.2,
                color: Colors.white,
              ),
            ),
          ],
        ),
        backgroundColor: const Color(0xFF1A1A1A),
        elevation: 4,
        actions: [
          IconButton(
            icon: const Icon(Icons.info_outline),
            onPressed: () {
              showDialog(
                context: context,
                builder: (c) => AlertDialog(
                  title: const Text("About Luartex V3.2"),
                  content: const Text("Luartex V3.2 is a high-performance Luau obfuscator featuring custom virtual machine generation, control flow flattening, and advanced opcode encryption."),
                  actions: [
                    TextButton(onPressed: () => Navigator.pop(c), child: const Text("Close"))
                  ],
                ),
              );
            },
          )
        ],
      ),
      body: Padding(
        padding: const EdgeInsets.all(16.0),
        child: isWide ? _buildDesktopLayout() : _buildMobileLayout(),
      ),
    );
  }

  Widget _buildDesktopLayout() {
    return Row(
      crossAxisAlignment: CrossAxisAlignment.start,
      children: [
        SizedBox(
          width: 300,
          child: _buildSettingsPanel(),
        ),
        const SizedBox(width: 16),
        Expanded(
          child: _buildEditorPanel(),
        ),
      ],
    );
  }

  Widget _buildMobileLayout() {
    return Column(
      children: [
        ExpansionTile(
          title: const Text("Obfuscation Settings", style: TextStyle(color: Color(0xFF00FF9D))),
          children: [_buildSettingsPanel()],
        ),
        const SizedBox(height: 16),
        Expanded(
          child: _buildEditorPanel(),
        ),
      ],
    );
  }

  Widget _buildSettingsPanel() {
    return Card(
      color: const Color(0xFF1E1E1E),
      shape: RoundedRectangleBorder(borderRadius: BorderRadius.circular(12)),
      child: Padding(
        padding: const EdgeInsets.all(16.0),
        child: Column(
          crossAxisAlignment: CrossAxisAlignment.start,
          mainAxisSize: MainAxisSize.min,
          children: [
            const Text(
              "Configuration",
              style: TextStyle(
                fontSize: 18,
                fontWeight: FontWeight.bold,
                color: Color(0xFF00FF9D),
              ),
            ),
            const Divider(color: Colors.grey),
            _buildSwitch("Custom VM", _enableCustomVM, (v) => setState(() => _enableCustomVM = v)),
            _buildSwitch("Control Flow Flattening", _enableControlFlowFlattening, (v) => setState(() => _enableControlFlowFlattening = v)),
            _buildSwitch("Opcode Obfuscation", _enableOpcodeObfuscation, (v) => setState(() => _enableOpcodeObfuscation = v)),
            _buildSwitch("String Encryption", _enableStringEncryption, (v) => setState(() => _enableStringEncryption = v)),
            _buildSwitch("Anti-Tamper", _enableAntiTamper, (v) => setState(() => _enableAntiTamper = v)),
            _buildSwitch("One Line Payload", _oneLinePayload, (v) => setState(() => _oneLinePayload = v)),
            const SizedBox(height: 20),
            SizedBox(
              width: double.infinity,
              child: ElevatedButton.icon(
                onPressed: _isProcessing ? null : _runObfuscation,
                icon: _isProcessing 
                  ? const SizedBox(width: 20, height: 20, child: CircularProgressIndicator(strokeWidth: 2, color: Colors.black)) 
                  : const Icon(Icons.code),
                label: Text(_isProcessing ? "PROCESSING..." : "OBFUSCATE"),
                style: ElevatedButton.styleFrom(
                  backgroundColor: const Color(0xFF00FF9D),
                  foregroundColor: Colors.black,
                  padding: const EdgeInsets.symmetric(vertical: 16),
                  textStyle: const TextStyle(fontWeight: FontWeight.bold, letterSpacing: 1),
                ),
              ),
            ),
          ],
        ),
      ),
    );
  }

  Widget _buildSwitch(String title, bool value, Function(bool) onChanged) {
    return Padding(
      padding: const EdgeInsets.symmetric(vertical: 4.0),
      child: SwitchListTile(
        title: Text(title, style: const TextStyle(fontSize: 14)),
        value: value,
        onChanged: onChanged,
        activeColor: const Color(0xFF00FF9D),
        contentPadding: EdgeInsets.zero,
        dense: true,
      ),
    );
  }

  Widget _buildEditorPanel() {
    return Column(
      children: [
        Expanded(
          flex: 1,
          child: _buildCodeInput("Input Luau Script", _inputController, false),
        ),
        const SizedBox(height: 16),
        Expanded(
          flex: 1,
          child: _buildCodeInput("Obfuscated Output", _outputController, true),
        ),
      ],
    );
  }

  Widget _buildCodeInput(String label, TextEditingController controller, bool readOnly) {
    return Container(
      decoration: BoxDecoration(
        color: const Color(0xFF1E1E1E),
        borderRadius: BorderRadius.circular(12),
        border: Border.all(color: Colors.grey.withOpacity(0.2)),
      ),
      child: Column(
        crossAxisAlignment: CrossAxisAlignment.start,
        children: [
          Padding(
            padding: const EdgeInsets.symmetric(horizontal: 16, vertical: 8),
            child: Row(
              mainAxisAlignment: MainAxisAlignment.spaceBetween,
              children: [
                Text(
                  label,
                  style: const TextStyle(
                    color: Colors.grey,
                    fontWeight: FontWeight.bold,
                    fontSize: 12,
                  ),
                ),
                if (readOnly)
                  IconButton(
                    icon: const Icon(Icons.copy, size: 18, color: Color(0xFF00FF9D)),
                    tooltip: "Copy to Clipboard",
                    onPressed: _copyToClipboard,
                  ),
              ],
            ),
          ),
          const Divider(height: 1, color: Colors.grey),
          Expanded(
            child: TextField(
              controller: controller,
              readOnly: readOnly,
              maxLines: null,
              expands: true,
              style: const TextStyle(
                fontFamily: 'monospace',
                fontSize: 14,
                color: Color(0xFFE0E0E0),
              ),
              decoration: const InputDecoration(
                contentPadding: EdgeInsets.all(16),
                border: InputBorder.none,
                hintText: "-- Enter your script here...",
                hintStyle: TextStyle(color: Colors.grey),
              ),
            ),
          ),
        ],
      ),
    );
  }
}
